mashin=["bmv","mz","ac"]
mashin.append('ghghh')
mashin.append('asy')
mashin.append('ll')
mashin.append('yuu')
mashin.append('uiui')
mashin.append('gh')
mashin.append('jk')
print(mashin)
mashin.insert(2 , "kkk")
print(mashin)
del mashin[4]
print(mashin)
del_item=mashin.pop(4)
print(mashin)
print(mashin[4])
print(mashin)
mashin.remove('bmv')
print(mashin)
